# 4.1.3 NumPyの各機能

In [1]:
import numpy as np

a = np.arange(3)
b = np.arange(-3, 3).reshape((2, 3))
c = np.arange(1, 7).reshape((2, 3))
d = np.arange(6).reshape((3, 2))
e = np.linspace(-1, 1, 10)
print("a:", a)
print("b:", b)
print("c:", c)
print("d:", d)
print("e:", e)

a: [0 1 2]
b: [[-3 -2 -1]
 [ 0  1  2]]
c: [[1 2 3]
 [4 5 6]]
d: [[0 1]
 [2 3]
 [4 5]]
e: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


In [2]:
print("a:", a.shape)
print("b:", b.shape)
print("c:", c.shape)
print("d:", d.shape)
print("e:", e.shape)

a: (3,)
b: (2, 3)
c: (2, 3)
d: (3, 2)
e: (10,)


In [3]:
li = [[-3, -2, -1],
      [0, 1, 2]]
new = []
for i, j in enumerate(li):
    new.append([])
    for k in j:
        new[i].append(abs(k))
new

[[3, 2, 1], [0, 1, 2]]

In [4]:
np.abs(b)

array([[3, 2, 1],
       [0, 1, 2]])

In [5]:
np.sin(e)

array([-0.84147098, -0.70169788, -0.52741539, -0.3271947 , -0.11088263,
        0.11088263,  0.3271947 ,  0.52741539,  0.70169788,  0.84147098])

In [6]:
np.cos(e)

array([0.54030231, 0.71247462, 0.84960756, 0.94495695, 0.99383351,
       0.99383351, 0.94495695, 0.84960756, 0.71247462, 0.54030231])

In [7]:
np.log(a)

/home/ubuntu/env36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718])

In [8]:
np.log10(c)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125]])

In [9]:
np.exp(a)

array([1.        , 2.71828183, 7.3890561 ])

In [10]:
a

array([0, 1, 2])

In [11]:
a + 10

array([10, 11, 12])

In [12]:
b

array([[-3, -2, -1],
       [ 0,  1,  2]])

In [13]:
a + b

array([[-3, -1,  1],
       [ 0,  2,  4]])

In [14]:
a1 = a[:, np.newaxis]
a1

array([[0],
       [1],
       [2]])

In [15]:
a + a1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [16]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c - np.mean(c)

array([[-2.5, -1.5, -0.5],
       [ 0.5,  1.5,  2.5]])

In [18]:
b * 2

array([[-6, -4, -2],
       [ 0,  2,  4]])

In [19]:
b ** 3

array([[-27,  -8,  -1],
       [  0,   1,   8]])

In [20]:
b - a

array([[-3, -3, -3],
       [ 0,  0,  0]])

In [21]:
a * b

array([[ 0, -2, -2],
       [ 0,  1,  4]])

In [22]:
a / c

array([[0.        , 0.5       , 0.66666667],
       [0.        , 0.2       , 0.33333333]])

In [23]:
c / a

/home/ubuntu/env36/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 2. , 1.5],
       [inf, 5. , 3. ]])

In [24]:
c / (a+1e-6)

array([[1.00000000e+06, 1.99999800e+00, 1.49999925e+00],
       [4.00000000e+06, 4.99999500e+00, 2.99999850e+00]])

In [25]:
np.dot(b, a)

array([-4,  5])

In [26]:
b @ a

array([-4,  5])

In [27]:
b @ d

array([[ -8, -14],
       [ 10,  13]])

In [28]:
d @ b

array([[  0,   1,   2],
       [ -6,  -1,   4],
       [-12,  -3,   6]])

In [29]:
a > 1

array([False, False,  True])

In [30]:
b > 0

array([[False, False, False],
       [False,  True,  True]])

In [31]:
np.count_nonzero(b > 0)

2

In [32]:
np.sum(b > 0)

2

In [33]:
np.any(b > 0)

True

In [34]:
np.all(b > 0)

False

In [35]:
b[b > 0]

array([1, 2])

In [36]:
b == c

array([[False, False, False],
       [False, False, False]])

In [37]:
a == b

array([[False, False, False],
       [ True,  True,  True]])

In [38]:
(b == c) | (a == b)

array([[False, False, False],
       [ True,  True,  True]])

In [39]:
b[(b == c) | (a == b)]

array([0, 1, 2])

In [40]:
np.allclose(b, c)

False

In [41]:
np.allclose(b, c, atol=10)

True

In [42]:
np.sum(a)

3

In [43]:
a.sum()

3