In [7]:
#　使用ライブラリ
    import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame
#　可視化ライブラリ
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

# 小数第三位まで表示
%precision 3


'%.3f'

In [8]:
data = np.array([9,2,3,4,10,6,8,1,5])

In [10]:
print(data)

[ 9  2  3  4 10  6  8  1  5]


In [15]:
print (data.ndim)
print (data.size)

1
9


In [20]:
print (data * 2)
print (data ** 2)
print (data / 5.0)
print (data / 3)

[ 2  4  6  8 10 12 16 18 20]
[  1   4   9  16  25  36  64  81 100]
[0.2 0.4 0.6 0.8 1.  1.2 1.6 1.8 2. ]
[0.333 0.667 1.    1.333 1.667 2.    2.667 3.    3.333]


In [25]:
#P38
data.sort()
print (data)
data[::-1].sort()
print (data)

[ 1  2  3  4  5  6  8  9 10]
[10  9  8  6  5  4  3  2  1]


In [134]:
print (f"min : {data.min()}")
print (f"max : {data.max()}")
#meanは平均値
print (f"mean: {data.mean()}")
print (f"sum : {data.sum()}")
#
print (f"cum : {data.cumsum()}")


min : 1
max : 10
mean: 5.333333333333333
sum : 48
cum : [10 19 27 33 38 42 45 47 48]


In [135]:
#乱数のseedを指定することで発生する乱数を固定する
random.seed(0)
rnd_data = random.randn(100)
print (rnd_data)

[ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411
  0.144  1.454  0.761  0.122  0.444  0.334  1.494 -0.205  0.313 -0.854
 -2.553  0.654  0.864 -0.742  2.27  -1.454  0.046 -0.187  1.533  1.469
  0.155  0.378 -0.888 -1.981 -0.348  0.156  1.23   1.202 -0.387 -0.302
 -1.049 -1.42  -1.706  1.951 -0.51  -0.438 -1.253  0.777 -1.614 -0.213
 -0.895  0.387 -0.511 -1.181 -0.028  0.428  0.067  0.302 -0.634 -0.363
 -0.672 -0.36  -0.813 -1.726  0.177 -0.402 -1.63   0.463 -0.907  0.052
  0.729  0.129  1.139 -1.235  0.402 -0.685 -0.871 -0.579 -0.312  0.056
 -1.165  0.901  0.466 -1.536  1.488  1.896  1.179 -0.18  -1.071  1.054
 -0.403  1.222  0.208  0.977  0.356  0.707  0.011  1.786  0.127  0.402]


In [71]:
#乱数から無作為に10個抽出する,replaceは重複の可否
print (random.choice(rnd_data,10,replace =  False))

[-0.187  0.777  1.951  0.901 -0.977 -1.253  0.444 -1.63   0.979 -1.165]


In [74]:
#1000000の乱数を発生させてその合計を算出する時間を計測
#圧倒的にnumpyの方が早い・・・・。
N = 10 ** 6
normal_data = [random.random() for _ in range(N)]

numpy_random_data = np.array(normal_data)

%timeit sum(normal_data)
%timeit np.sum(numpy_random_data)

4.6 ms ± 96.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
378 µs ± 6.33 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [140]:
print ("# 9のリストを生成して、3x3の行列に整形する")
ary = np.arange(9).reshape(3,3)
print (ary)
print ("# 12のリストを生成して、4x3の行列に整形する")
ary = np.arange(12).reshape(4,3)
print (ary)

print ("#2行目を取得")
print (ary[1,:])

print ("#2列目を取得")
print (ary[:,1])

# 9のリストを生成して、3x3の行列に整形する
[[0 1 2]
 [3 4 5]
 [6 7 8]]
# 12のリストを生成して、4x3の行列に整形する
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
#2行目を取得
[3 4 5]
#2行目を取得
[ 1  4  7 10]


In [ ]:
#行列計算例

In [88]:
print (ary[:,1])

[ 1  4  7 10]


In [100]:
ary1 = np.arange(4).reshape(2,2)
print (ary1)
ary2 = np.array([4,5,2,3]).reshape(2,2)
print (ary2)
# 行列の積
print (np.dot(ary1,ary2))

# 要素同士の和
print (ary1 * ary2)

#要素が0,1の行列
print (np.zeros((2,3), dtype= np.int64))
print (np.ones((3,3), dtype= np.int64))



[[0 1]
 [2 3]]
[[4 5]
 [2 3]]
[[ 2  3]
 [14 19]]
[[0 5]
 [4 9]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [143]:
#練習課題2-1
ary3 = np.arange(51)
print (f"合計は{ary3.sum()}")
print (f"合計は{np.sum(ary3)}")



合計は1275
合計は1275


In [123]:
#練習課題2-2
ary4 = random.rand(10)
print (f"{ary4}")
print (f"最大値は{np.max(ary4)},最小値は{np.min(ary4)},平均値は{np.sum(ary4)/len(ary4)} or {np.average(ary4)}")

[0.049 0.406 0.968 0.803 0.978 0.358 0.733 0.482 0.591 0.295]
最大値は0.9783812610990192,最小値は0.048667475255877,平均値は0.5664273696089843 or 0.5664273696089843


In [129]:
#練習課題2-3
ary5 = np.ones((5,5))
ary5 *= 3
print (np.dot(ary5,ary5))

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
[[45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]
 [45. 45. 45. 45. 45.]]
