In [2]:
import numpy as np
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
sns.set()
%matplotlib inline
%precision 3

'%.3f'

In [21]:
sample_array = np.arange(10)
print (f"sample_ary:{sample_array}")

sample_ary:[0 1 2 3 4 5 6 7 8 9]


In [10]:
sample_array_slice = sample_array[0:5]
sample_array_slice

slice[0:5]:[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [13]:
sample_array[2] = 10
sample_array,sample_array_slice

(array([ 0,  1, 10,  3,  4,  5,  6,  7,  8,  9]), array([ 0,  1, 10,  3,  4]))

In [18]:
sample_array[0:3] = [10,9,8]

In [20]:
sample_array,sample_array_slice

(array([10,  9,  8,  3,  4,  5,  6,  7,  8,  9]), array([10,  9,  8,  3,  4]))

In [23]:
copy_array = sample_array.copy()

In [25]:
copy_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
sample_array[0:3] = [10,9,8]

In [30]:
sample_array,copy_array

(array([10,  9,  8,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [35]:
sample_names = np.array(['a','b','c','d','e'])
np.random.seed(0)
data = np.random.randn(5,5)
print (sample_names)
print (data)

['a' 'b' 'c' 'd' 'e']
[[ 1.764  0.4    0.979  2.241  1.868]
 [-0.977  0.95  -0.151 -0.103  0.411]
 [ 0.144  1.454  0.761  0.122  0.444]
 [ 0.334  1.494 -0.205  0.313 -0.854]
 [-2.553  0.654  0.864 -0.742  2.27 ]]


In [61]:
# TODO:複数条件を入れる方法（例えば、aとeとか）
sample_names == 'a'

array([ True, False, False, False, False])

In [62]:
data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [64]:
cond_data = np.array([True,False,True,True,False])
data[cond_data]

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [ 0.144,  1.454,  0.761,  0.122,  0.444],
       [ 0.334,  1.494, -0.205,  0.313, -0.854]])

In [66]:
x_array = np.array([1,2,3,4,5])
y_array = np.array([100,200,300,400,500])
np.where(cond_data,x_array,y_array)

array([  1, 200,   3,   4, 500])

In [71]:
#練習問題5-1
data[sample_names == 'b']

array([[-0.977,  0.95 , -0.151, -0.103,  0.411]])

In [73]:
#練習問題5-2
data[sample_names != 'c']

array([[ 1.764,  0.4  ,  0.979,  2.241,  1.868],
       [-0.977,  0.95 , -0.151, -0.103,  0.411],
       [ 0.334,  1.494, -0.205,  0.313, -0.854],
       [-2.553,  0.654,  0.864, -0.742,  2.27 ]])

In [75]:
#練習問題5-3
cond_data = np.array([False,False,True,True,False])
np.where (cond_data,x_array,y_array)

array([100, 200,   3,   4, 500])

In [78]:
np.unique(cond_data)

array([False,  True])

In [83]:
np.unique(cond_data)

array([False,  True])

In [89]:
sample_data = np.arange(10)

In [92]:
#ユニバーサル関数
np.sqrt(sample_data)
np.exp(sample_data)

array([1.000e+00, 2.718e+00, 7.389e+00, 2.009e+01, 5.460e+01, 1.484e+02,
       4.034e+02, 1.097e+03, 2.981e+03, 8.103e+03])

In [95]:
sample_multi_ary = np.arange(9).reshape(3,3)
sample_multi_ary

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [101]:
sample_multi_ary.max()

8

In [104]:
sample_multi_ary.sum(),sample_multi_ary.mean()

(36, 4.0)

In [108]:
sample_multi_ary.sum(axis = 1)#行の合計

array([ 3, 12, 21])

In [111]:
sample_multi_ary.sum(axis = 0)#列の合計

array([ 9, 12, 15])

In [113]:
cond_data.any()

True

In [115]:
cond_data.all()

False

In [117]:
cond_data.sum()

2

In [132]:
np.any((3 < sample_multi_ary)  & (sample_multi_ary < 5))

True

In [137]:
np.diag(sample_multi_ary)

array([0, 4, 8])

In [139]:
np.trace(sample_multi_ary)

12

In [143]:
sample_multi_array2 = np.arange(16).reshape(4,4)
sample_multi_array2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [145]:
#練習問題5-4
print (f"最大値：{sample_multi_array2.max()}")
print (f"最小値：{sample_multi_array2.min()}")
print (f"合計値：{sample_multi_array2.sum()}")
print (f"平均値：{sample_multi_array2.mean()}")

最大値：15
最小値：0
合計値：120
平均値：7.5


In [148]:
np.diag(sample_multi_array2)

array([ 0,  5, 10, 15])

In [152]:
np.trace(sample_multi_array2)

30

In [154]:
sample_array = np.arange(10)
sample_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
sample_array2 = sample_array.reshape(2,5)
sample_array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [160]:
sample_array2.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [166]:
sample_array2 = np.array([[1,2,3],[4,5,6]])
sample_array3 = np.array([[7,8,9],[10,11,12]])
sample_array2
sample_array3

array([[ 7,  8,  9],
       [10, 11, 12]])

In [169]:
np.concatenate([sample_array2,sample_array3],axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [176]:
np.concatenate([sample_array2,sample_array3],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [173]:
np.vstack([sample_array2,sample_array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [180]:
np.hstack([sample_array2,sample_array3])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [187]:
np.vstack([sample_array2,sample_array3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [189]:
first, second, third = np.split(np.vstack([sample_array2,sample_array3]),[1,3])

In [191]:
first

array([[1, 2, 3]])

In [194]:
second

array([[4, 5, 6],
       [7, 8, 9]])

In [198]:
second[0],second[1]

(array([4, 5, 6]), array([7, 8, 9]))

In [199]:
third

array([[10, 11, 12]])

In [202]:
first.repeat(5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [204]:
first + 5

array([[6, 7, 8]])

In [208]:
#練習問題5-7
sample_array1 = np.arange(12).reshape(3,4)
sample_array2 = np.arange(12,24).reshape(3,4)

In [214]:
vmerge_array = np.vstack([sample_array1,sample_array2])
vmerge_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [217]:
hmerge_array = np.hstack([sample_array1,sample_array2])
hmerge_array

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [219]:
sample_list = [1,2,3,4,5]
np_list = np.array(sample_list)
np_list + 4

array([5, 6, 7, 8, 9])