In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
b = np.array([[1,2,3],[4,5,6]])
print (b)

[[1 2 3]
 [4 5 6]]


In [7]:
c=np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
print (c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


In [10]:
d = np.zeros(8)
e = np.ones(8)
f = np.arange(8)
print (d)
print (e)
print (f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


In [14]:
print (np.shape(c))

(2, 2, 3)


In [16]:
print (len(c))

2


In [18]:
print (b + 3)
print (b * 3)

[[4 5 6]
 [7 8 9]]
[[ 3  6  9]
 [12 15 18]]


In [20]:
print (b * c)

[[[ 0  2  6]
  [12 20 30]]

 [[ 5  8  9]
  [ 8  5  0]]]


In [23]:
print (b)
print ("-----")
print (c)
print ("-----")

print (b + c)

[[1 2 3]
 [4 5 6]]
-----
[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]
-----
[[[ 1  3  5]
  [ 7  9 11]]

 [[ 6  6  6]
  [ 6  6  6]]]


In [25]:
g = b + c

In [26]:
print (g[1])

[[6 6 6]
 [6 6 6]]
